# Generated by Django 5.2.9 on 2025-12-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_codigo', models.CharField(help_text='Código único do projeto', max_length=50, unique=True, verbose_name='CF - Código')),
                ('cliente', models.CharField(help_text='Nome do cliente', max_length=200, verbose_name='Cliente')),
                ('plataforma', models.CharField(choices=[('CHINA_FACIL', 'China Fácil'), ('ALIBABA', 'Alibaba'), ('1688', '1688'), ('TAOBAO', 'Taobao'), ('OUTROS', 'Outros')], default='CHINA_FACIL', max_length=50, verbose_name='Plataforma')),
                ('inicio_sourcing', models.DateField(default=django.utils.timezone.now, verbose_name='Início do Sourcing')),
                ('status', models.CharField(choices=[('INICIAR_SOURCING', 'Iniciar Sourcing'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_FORNECEDOR', 'Aguardando Fornecedor'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='INICIAR_SOURCING', max_length=50, verbose_name='Status')),
                ('fornecedor', models.CharField(blank=True, help_text='Nome do fornecedor', max_length=200, null=True, verbose_name='Fornecedor')),
                ('descricao', models.TextField(help_text='Descrição detalhada do projeto', verbose_name='Descrição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Atualização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_atualizacao'],
                'indexes': [models.Index(fields=['cf_codigo'], name='projetos_pr_cf_codi_c5aa23_idx'), models.Index(fields=['cliente'], name='projetos_pr_cliente_fde2e0_idx'), models.Index(fields=['data_atualizacao'], name='projetos_pr_data_at_ff02e2_idx')],
            },
        ),
    ]
