# Generated by Django 5.2.9 on 2025-12-09 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Login')),
                ('data_logout', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Logout')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador', verbose_name='User Agent')),
                ('localizacao', models.CharField(blank=True, help_text='Cidade/Estado/País', max_length=200, verbose_name='Localização')),
                ('sessao_ativa', models.BooleanField(default=True, verbose_name='Sessão Ativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Registros de Acesso',
                'ordering': ['-data_login'],
                'indexes': [models.Index(fields=['usuario', '-data_login'], name='usuarios_re_usuario_3b2cce_idx'), models.Index(fields=['sessao_ativa'], name='usuarios_re_sessao__a27c5d_idx')],
            },
        ),
    ]
